steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/khhini-repository/go-sample-app:$SHORT_SHA
    id: Pull

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/khhini-repository/go-sample-app:$SHORT_SHA
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/khhini-repository/go-sample-app:$TAG_NAME
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/khhini-repository/go-sample-app:$TAG_NAME
    id: Push

  - name: 'gcr.io/cloud-builders/git'
    id: Retrieve SSH key
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts

    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: Clone ENV repo
    args:
    - clone
    - '-b'
    - kustomize
    - git@github.com:khhini/riset-devsecops-sample-app-env.git
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      cd riset-devsecops-sample-app-env
      sed -i "s#newTag:.*#newTag: \"$TAG_NAME\"#g" overlays/prod/kustomization.yaml

  # This step pushes the manifest back to hello-cloudbuild-env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Push manifest
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      set -x && \
      cd riset-devsecops-sample-app-env
      git config --global user.email $(git log --format='%an <%ae>' -n 1 HEAD)
      git config --global user.name $(git log --format='%an <%ae>' -n 1 HEAD)
      git add overlays/stage/kustomization.yaml
      git commit -m "Relase ${TAG_NAME} from image asia-southeast2-docker.pkg.dev/$PROJECT_ID/khhini-repository/go-sample-app:${SHORT_SHA}
      Built from commit https://github.com/khhini/${REPO_NAME}/commit/${COMMIT_SHA}
      Author: $(git log --format='%an <%ae>' -n 1 HEAD)"
      git push origin kustomize
    volumes:
    - name: 'ssh'
      path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/1078293032607/secrets/github_ssh_keys/versions/1
    env: 'SSH_KEY'